In [20]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('mergedTrainingData.csv')
df

Unnamed: 0  week  season              Team          opponent  code  \
0              1    10    2021         Air Force              Army  2005   
1              2    10    2021             Akron  Western Michigan  2006   
2              3    10    2021           Alabama               LSU   333   
3              4    10    2021           Arizona        California    12   
4              5    10    2021     Arizona State               USC     9   
...          ...   ...     ...               ...               ...   ...   
5641        5642     9    2024     West Virginia           Arizona   277   
5642        5643     9    2024  Western Kentucky    Kennesaw State    98   
5643        5644     9    2024  Western Michigan        Kent State  2711   
5644        5645     9    2024         Wisconsin        Penn State   275   
5645        5646     9    2024           Wyoming        Utah State  2751   

             date win_loss     OT OT_num  ...  home_game           CONF  SOR  \
0      Sat, Nov 6        L   True         ...       True  Mountain West   33   
1      Tue, Nov 9        L  False    NaN  ...      False            MAC  127   
2      Sat, Nov 6        W  False    NaN  ...       True            SEC    2   
3      Sat, Nov 6        W  False    NaN  ...       True         Pac-12  122   
4      Sat, Nov 6        W  False    NaN  ...       True         Pac-12   49   
...           ...      ...    ...    ...  ...        ...            ...  ...   
5641  Sat, Oct 26        W  False    NaN  ...      False         Big 12   58   
5642  Wed, Oct 30        W  False    NaN  ...       True           CUSA   84   
5643  Sat, Oct 26        W  False    NaN  ...       True            MAC  103   
5644  Sat, Oct 26        L  False    NaN  ...       True        Big Ten   55   
5645  Sat, Oct 26        L  False    NaN  ...       True  Mountain West  119   

      FPI  SOS   GC  AVGWP AP_rank  opponent_rank  rank_change  
0      66  110   24      6     NaN            NaN          0.0  
1     128   67  118    125     NaN            NaN          0.0  
2       2    1    2      3     3.0            NaN         -1.0  
3     106   71  110    122     NaN            NaN          0.0  
4      39   61   61     63     NaN            NaN          0.0  
...   ...  ...  ...    ...     ...            ...          ...  
5641   63   54   64     81     NaN            NaN          0.0  
5642   99   80   77     56     NaN            NaN          0.0  
5643  108   70  103     87     NaN            NaN          0.0  
5644   47   32   41     76     NaN            3.0          0.0  
5645  113   97  124    125     NaN            NaN          0.0  

[5646 rows x 26 columns]

In [3]:
df['week'].isna().sum()

np.int64(0)

In [5]:
unique_week = df['week'].unique()
unique_week = sorted(unique_week)
unique_week

[np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18)]

In [10]:
df['week'].value_counts().sort_index()

week
2     362
3     407
4     447
5     458
6     428
7     423
8     440
9     443
10    464
11    465
12    477
13    462
14    282
15     68
16     13
17      3
18      4
Name: count, dtype: int64

In [11]:
df['week'].unique()

array([10, 11, 12, 13, 14, 15, 16, 17, 18,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
df['season'].isna().sum()

np.int64(0)

In [13]:
df['season'].value_counts().sort_index()

season
2021    1379
2022    1391
2023    1412
2024    1464
Name: count, dtype: int64

In [14]:
df['season'].unique()

array([2021, 2022, 2023, 2024])

In [15]:
unique_season = df['season'].unique()
unique_season = sorted(unique_season)
unique_season

[np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [16]:
df['Team'].isna().sum()

np.int64(0)

In [17]:
df['Team'].unique()

array(['Air Force', 'Akron', 'Alabama', 'Arizona', 'Arizona State',
       'Arkansas', 'Army', 'Auburn', 'Ball State', 'Baylor',
       'Boise State', 'Boston College', 'Bowling Green', 'Buffalo',
       'Central Michigan', 'Charlotte', 'Cincinnati', 'Coastal Carolina',
       'Colorado', 'Colorado State', 'Duke', 'East Carolina',
       'Eastern Michigan', 'Florida', 'Florida Atlantic',
       'Florida International', 'Florida State', 'Fresno State',
       'Georgia', 'Georgia Southern', 'Georgia State', 'Georgia Tech',
       "Hawai'i", 'Houston', 'Illinois', 'Indiana', 'Iowa', 'Iowa State',
       'Kansas', 'Kansas State', 'Kent State', 'Kentucky', 'Liberty',
       'Louisiana', 'Louisiana Tech', 'Louisville', 'LSU', 'Marshall',
       'Maryland', 'Memphis', 'Miami', 'Miami (OH)', 'Michigan',
       'Michigan State', 'Middle Tennessee', 'Minnesota',
       'Mississippi State', 'Missouri', 'Navy', 'NC State', 'Nebraska',
       'New Mexico', 'North Carolina', 'North Texas', 'Northern

In [18]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

['Air Force',
 'Akron',
 'Alabama',
 'App State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Army',
 'Auburn',
 'BYU',
 'Ball State',
 'Baylor',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Buffalo',
 'California',
 'Central Michigan',
 'Charlotte',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colorado',
 'Colorado State',
 'Duke',
 'East Carolina',
 'Eastern Michigan',
 'Florida',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fresno State',
 'Georgia',
 'Georgia Southern',
 'Georgia State',
 'Georgia Tech',
 "Hawai'i",
 'Houston',
 'Illinois',
 'Indiana',
 'Iowa',
 'Iowa State',
 'Jacksonville State',
 'James Madison',
 'Kansas',
 'Kansas State',
 'Kennesaw State',
 'Kent State',
 'Kentucky',
 'LSU',
 'Liberty',
 'Louisiana',
 'Louisiana Tech',
 'Louisville',
 'Marshall',
 'Maryland',
 'Massachusetts',
 'Memphis',
 'Miami',
 'Miami (OH)',
 'Michigan',
 'Michigan State',
 'Middle Tennessee',
 'Minnesota',
 'Mississippi State',
 '

In [21]:
df['Team'].value_counts().sort_index()

Team
Air Force                44
Akron                    41
Alabama                  47
App State                10
Arizona                  42
Arizona State            46
Arkansas                 45
Arkansas State           42
Army                     36
Auburn                   43
BYU                      42
Ball State               42
Baylor                   45
Boise State              44
Boston College           41
Bowling Green            44
Buffalo                  43
California               43
Central Michigan         42
Charlotte                41
Cincinnati               45
Clemson                  44
Coastal Carolina         39
Colorado                 44
Colorado State           39
Duke                     42
East Carolina            40
Eastern Michigan         45
Florida                  41
Florida Atlantic         40
Florida International    40
Florida State            44
Fresno State             39
Georgia                  49
Georgia Southern         42
Georgia State  

In [22]:
df['opponent'].isna().sum()

np.int64(0)

In [23]:
df['opponent'].value_counts().sort_index()

opponent
Air Force                47
Akron                    40
Alabama                  47
App State                10
Arizona                  42
Arizona State            46
Arkansas                 45
Arkansas State           44
Army                     43
Auburn                   44
BYU                      44
Ball State               41
Baylor                   45
Boise State              46
Boston College           43
Bowling Green            41
Buffalo                  44
California               40
Central Michigan         41
Charlotte                40
Cincinnati               45
Clemson                  45
Coastal Carolina         40
Colorado                 45
Colorado State           39
Duke                     43
East Carolina            39
Eastern Michigan         44
Florida                  43
Florida Atlantic         40
Florida International    42
Florida State            42
Fresno State             43
Georgia                  51
Georgia Southern         43
Georgia Sta

In [26]:
unique_opponent = df['opponent'].unique()
unique_opponent = sorted(unique_opponent)
unique_opponent

['Air Force',
 'Akron',
 'Alabama',
 'App State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Army',
 'Auburn',
 'BYU',
 'Ball State',
 'Baylor',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Buffalo',
 'California',
 'Central Michigan',
 'Charlotte',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colorado',
 'Colorado State',
 'Duke',
 'East Carolina',
 'Eastern Michigan',
 'Florida',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fresno State',
 'Georgia',
 'Georgia Southern',
 'Georgia State',
 'Georgia Tech',
 "Hawai'i",
 'Houston',
 'Illinois',
 'Indiana',
 'Iowa',
 'Iowa State',
 'Jacksonville State',
 'James Madison',
 'Kansas',
 'Kansas State',
 'Kennesaw State',
 'Kent State',
 'Kentucky',
 'LSU',
 'Liberty',
 'Louisiana',
 'Louisiana Tech',
 'Louisville',
 'Marshall',
 'Maryland',
 'Massachusetts',
 'Memphis',
 'Miami',
 'Miami (OH)',
 'Michigan',
 'Michigan State',
 'Middle Tennessee',
 'Minnesota',
 'Mississippi State',
 '

In [27]:
df['opponent'].unique()

array(['Army', 'Western Michigan', 'LSU', 'California', 'USC',
       'Mississippi State', 'Air Force', 'Texas A&M', 'Northern Illinois',
       'TCU', 'Fresno State', 'Virginia Tech', 'Toledo', 'Miami (OH)',
       'Kent State', 'Louisiana Tech', 'Tulsa', 'Georgia State',
       'Oregon State', 'Wyoming', 'Pittsburgh', 'Temple', 'Ohio',
       'South Carolina', 'Old Dominion', 'NC State', 'San Diego State',
       'Missouri', 'Coastal Carolina', 'Louisiana', 'Miami', 'Utah State',
       'South Florida', 'Rutgers', 'Michigan', 'Northwestern', 'Texas',
       'Kansas State', 'Kansas', 'Central Michigan', 'Tennessee',
       'Ole Miss', 'Troy', 'UAB', 'Clemson', 'Alabama',
       'Florida Atlantic', 'Penn State', 'SMU', 'Georgia Tech', 'Buffalo',
       'Indiana', 'Purdue', 'Florida International', 'Illinois',
       'Arkansas', 'Georgia', 'Notre Dame', 'North Carolina', 'UNLV',
       'Wake Forest', 'Southern Miss', 'Ball State', 'Iowa', 'Navy',
       'Eastern Michigan', 'Nebraska', '

In [28]:
df['code'].isna().sum()

np.int64(0)

In [29]:
df['code'].unique()

array([2005, 2006,  333,   12,    9,    8,  349,    2, 2050,  239,   68,
        103,  189, 2084, 2117, 2429, 2132,  324,   38,   36,  150,  151,
       2199,   57, 2226, 2229,   52,  278,   61,  290, 2247,   59,   62,
        248,  356,   84, 2294,   66, 2305, 2306, 2309,   96, 2335,  309,
       2348,   97,   99,  276,  120,  235, 2390,  193,  130,  127, 2393,
        135,  344,  142, 2426,  154,  158,  167,  153,  249, 2459,   77,
         87,  195,  194,  197,  295,  145, 2483,  204,  213,  221, 2509,
        242,  164,   21,   23, 2567,    6, 2579,   58, 2572,   24, 2628,
        218, 2633,  251,  245,  326, 2649, 2653, 2655,  202,    5, 2116,
         26, 2433, 2439,   30,  254,  328, 2638, 2636,  259,  264,  277,
         98, 2711,  275, 2751,  252,   25,  228,  256,  166,  201,  183,
       2641,   41,  258,  265, 2032,   55,  113, 2440,  238, 2026,  338,
       2534])

In [30]:
df['code'].value_counts().sort_index()

code
2       43
5       44
6       43
8       45
9       46
12      42
21      41
23      41
24      41
25      43
26      43
30      47
36      39
38      44
41      40
52      44
55      23
57      41
58      40
59      42
61      49
62      39
66      45
68      44
77      41
84      41
87      48
96      43
97      45
98      47
99      45
103     41
113     34
120     45
127     42
130     51
135     44
142     46
145     45
150     42
151     40
153     38
154     88
158     41
164     44
166     40
167     41
183     42
189     44
193     45
194     49
195     43
197     46
201     45
202     44
204     43
213     47
218     40
221     43
228     44
235     46
238     41
239     45
242     40
245     42
248     42
249     43
251     49
252     42
254     46
256     29
258     42
259     44
264     48
265     41
275     46
276     42
277     42
278     39
290     42
295     39
309     47
324     39
326     41
328     39
333     47
338      9
344     44
349     36
356     44
2005 

In [31]:
df['date'].isna().sum()

np.int64(0)

In [32]:
df['date'].unique()

array(['Sat, Nov 6', 'Tue, Nov 9', 'Wed, Nov 10', 'Fri, Nov 5',
       'Sat, Nov 13', 'Sat, Oct 30', 'Thu, Nov 4', 'Sat, Nov 5',
       'Tue, Nov 8', 'Sat, Nov 12', 'Fri, Nov 4', 'Wed, Nov 9',
       'Sat, Oct 29', 'Thu, Nov 10', 'Thu, Nov 3', 'Sat, Nov 4',
       'Wed, Nov 8', 'Tue, Nov 7', 'Fri, Nov 3', 'Sat, Nov 11',
       'Thu, Nov 2', 'Wed, Oct 25', 'Tue, Oct 24', 'Sat, Oct 28',
       'Fri, Nov 10', 'Thu, Nov 9', 'Sat, Nov 2', 'Tue, Nov 12',
       'Sat, Nov 9', 'Tue, Nov 5', 'Fri, Nov 8', 'Thu, Oct 31',
       'Thu, Nov 7', 'Sat, Oct 26', 'Wed, Nov 6', 'Fri, Nov 1',
       'Sat, Nov 16', 'Sat, Nov 20', 'Wed, Nov 17', 'Fri, Nov 12',
       'Tue, Nov 16', 'Thu, Nov 11', 'Tue, Nov 15', 'Sat, Nov 19',
       'Wed, Nov 16', 'Fri, Nov 11', 'Thu, Nov 17', 'Fri, Nov 18',
       'Tue, Nov 14', 'Sat, Nov 18', 'Wed, Nov 15', 'Wed, Nov 13',
       'Fri, Nov 15', 'Sat, Nov 23', 'Thu, Nov 14', 'Fri, Nov 19',
       'Sat, Nov 27', 'Tue, Nov 23', 'Fri, Nov 26', 'Thu, Nov 18',
       'Sat, Nov 

In [33]:
df['date'].value_counts().sort_index()

date
Fri, Dec 1       4
Fri, Dec 16      3
Fri, Dec 17      3
Fri, Dec 2       6
Fri, Dec 20      6
Fri, Dec 22      2
Fri, Dec 23      4
Fri, Dec 27      9
Fri, Dec 29      6
Fri, Dec 3       4
Fri, Dec 30      7
Fri, Dec 31      6
Fri, Dec 6       6
Fri, Jan 10      2
Fri, Jan 3       2
Fri, Nov 1       5
Fri, Nov 10      4
Fri, Nov 11      6
Fri, Nov 12      4
Fri, Nov 15      8
Fri, Nov 17      4
Fri, Nov 18      4
Fri, Nov 19     10
Fri, Nov 22      5
Fri, Nov 24     24
Fri, Nov 25     24
Fri, Nov 26     31
Fri, Nov 29     23
Fri, Nov 3       4
Fri, Nov 4       5
Fri, Nov 5       4
Fri, Nov 8       9
Fri, Oct 1       6
Fri, Oct 11      6
Fri, Oct 13      6
Fri, Oct 14      4
Fri, Oct 15      7
Fri, Oct 18      8
Fri, Oct 20      2
Fri, Oct 21      4
Fri, Oct 22      7
Fri, Oct 25      6
Fri, Oct 27      2
Fri, Oct 28      4
Fri, Oct 29      4
Fri, Oct 4       8
Fri, Oct 6       4
Fri, Oct 7       7
Fri, Oct 8       6
Fri, Sep 1       1
Fri, Sep 10      4
Fri, Sep 13      4
Fri, Se

In [34]:
unique_date = df['date'].unique()
unique_date = sorted(unique_date)
unique_date

['Fri, Dec 1',
 'Fri, Dec 16',
 'Fri, Dec 17',
 'Fri, Dec 2',
 'Fri, Dec 20',
 'Fri, Dec 22',
 'Fri, Dec 23',
 'Fri, Dec 27',
 'Fri, Dec 29',
 'Fri, Dec 3',
 'Fri, Dec 30',
 'Fri, Dec 31',
 'Fri, Dec 6',
 'Fri, Jan 10',
 'Fri, Jan 3',
 'Fri, Nov 1',
 'Fri, Nov 10',
 'Fri, Nov 11',
 'Fri, Nov 12',
 'Fri, Nov 15',
 'Fri, Nov 17',
 'Fri, Nov 18',
 'Fri, Nov 19',
 'Fri, Nov 22',
 'Fri, Nov 24',
 'Fri, Nov 25',
 'Fri, Nov 26',
 'Fri, Nov 29',
 'Fri, Nov 3',
 'Fri, Nov 4',
 'Fri, Nov 5',
 'Fri, Nov 8',
 'Fri, Oct 1',
 'Fri, Oct 11',
 'Fri, Oct 13',
 'Fri, Oct 14',
 'Fri, Oct 15',
 'Fri, Oct 18',
 'Fri, Oct 20',
 'Fri, Oct 21',
 'Fri, Oct 22',
 'Fri, Oct 25',
 'Fri, Oct 27',
 'Fri, Oct 28',
 'Fri, Oct 29',
 'Fri, Oct 4',
 'Fri, Oct 6',
 'Fri, Oct 7',
 'Fri, Oct 8',
 'Fri, Sep 1',
 'Fri, Sep 10',
 'Fri, Sep 13',
 'Fri, Sep 15',
 'Fri, Sep 16',
 'Fri, Sep 17',
 'Fri, Sep 2',
 'Fri, Sep 20',
 'Fri, Sep 22',
 'Fri, Sep 23',
 'Fri, Sep 24',
 'Fri, Sep 27',
 'Fri, Sep 29',
 'Fri, Sep 30',
 'Fri, Se

In [35]:
df['win_loss'].isna().sum()

np.int64(0)

In [36]:
df['win_loss'].unique()

array(['L', 'W'], dtype=object)

In [37]:
df['win_loss'].value_counts().sort_index()

win_loss
L    2841
W    2805
Name: count, dtype: int64

In [38]:
df['OT'].isna().sum()

np.int64(0)

In [39]:
df['OT'].unique()

array([ True, False])

In [40]:
df['OT'].value_counts().sort_index()

OT
False    5391
True      255
Name: count, dtype: int64

In [41]:
df['OT_num'].isna().sum()

np.int64(5391)

In [42]:
df['OT_num'].unique()

array([' ', nan, '2', '3', '4', '8', '6', '9'], dtype=object)

In [43]:
df['OT_num'].value_counts().sort_index()

OT_num
     164
2     65
3      8
4     12
6      2
8      2
9      2
Name: count, dtype: int64

In [45]:
df['home_game'].isna().sum()

np.int64(0)